# Form implementation generated from reading ui file 'd:\Personal\Projects\muhendislik_tasarimi_proje\source_codes\project\ui\pref.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(840, 500))
        MainWindow.setMaximumSize(QtCore.QSize(9999, 9999))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(840, 500))
        self.centralwidget.setMaximumSize(QtCore.QSize(840, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 842, 502))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.hmain_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.hmain_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.hmain_layout.setContentsMargins(0, 0, 0, 0)
        self.hmain_layout.setSpacing(0)
        self.hmain_layout.setObjectName("hmain_layout")
        self.menu_page = QtWidgets.QWidget(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_page.sizePolicy().hasHeightForWidth())
        self.menu_page.setSizePolicy(sizePolicy)
        self.menu_page.setMinimumSize(QtCore.QSize(0, 0))
        self.menu_page.setMaximumSize(QtCore.QSize(999, 999))
        self.menu_page.setStyleSheet("background-color:#1F1F1F;")
        self.menu_page.setObjectName("menu_page")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.menu_page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 110, 171, 162))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vmenu_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vmenu_layout.setContentsMargins(0, 0, 0, 0)
        self.vmenu_layout.setSpacing(0)
        self.vmenu_layout.setObjectName("vmenu_layout")
        self.menu_general_button = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_general_button.sizePolicy().hasHeightForWidth())
        self.menu_general_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        self.menu_general_button.setFont(font)
        self.menu_general_button.setStyleSheet("QRadioButton {\n"
"    padding: 10px;\n"
"    border: none;\n"
"    color: white; \n"
"}\n"
"QRadioButton:hover {\n"
"    background-color: #484848;\n"
"}\n"
"QRadioButton::indicator {\n"
" \n"
"\n"
"    border: none;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"     border-left: 6px solid #1e90ff; \n"
"}\n"
"\n"
"")
        self.menu_general_button.setChecked(True)
        self.menu_general_button.setObjectName("menu_general_button")
        self.vmenu_layout.addWidget(self.menu_general_button)
        self.menu_mal_data_button = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_mal_data_button.sizePolicy().hasHeightForWidth())
        self.menu_mal_data_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        self.menu_mal_data_button.setFont(font)
        self.menu_mal_data_button.setStyleSheet("QRadioButton {\n"
"    padding: 10px;\n"
"    border: none;\n"
"    color: white; \n"
"}\n"
"QRadioButton:hover {\n"
"    background-color: #484848;\n"
"}\n"
"QRadioButton::indicator {\n"
" \n"
"\n"
"    border: none;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"     border-left: 6px solid #1e90ff; \n"
"}\n"
"\n"
"")
        self.menu_mal_data_button.setChecked(False)
        self.menu_mal_data_button.setObjectName("menu_mal_data_button")
        self.vmenu_layout.addWidget(self.menu_mal_data_button)
        self.menu_fw_button = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_fw_button.sizePolicy().hasHeightForWidth())
        self.menu_fw_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        self.menu_fw_button.setFont(font)
        self.menu_fw_button.setStyleSheet("QRadioButton {\n"
"    padding: 10px;\n"
"    border: none;\n"
"    color: white; \n"
"}\n"
"QRadioButton:hover {\n"
"    background-color: #484848;\n"
"}\n"
"QRadioButton::indicator {\n"
" \n"
"\n"
"    border: none;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"     border-left: 6px solid #1e90ff; \n"
"}\n"
"\n"
"")
        self.menu_fw_button.setChecked(False)
        self.menu_fw_button.setObjectName("menu_fw_button")
        self.vmenu_layout.addWidget(self.menu_fw_button)
        self.menu_stat_button = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_stat_button.sizePolicy().hasHeightForWidth())
        self.menu_stat_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        self.menu_stat_button.setFont(font)
        self.menu_stat_button.setStyleSheet("QRadioButton {\n"
"    padding: 10px;\n"
"    border: none;\n"
"    color: white; \n"
"}\n"
"QRadioButton:hover {\n"
"    background-color: #484848;\n"
"}\n"
"QRadioButton::indicator {\n"
" \n"
"\n"
"    border: none;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"     border-left: 6px solid #1e90ff; \n"
"}\n"
"\n"
"")
        self.menu_stat_button.setChecked(False)
        self.menu_stat_button.setObjectName("menu_stat_button")
        self.vmenu_layout.addWidget(self.menu_stat_button)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.menu_page)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(170, 0, 672, 500))
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setMaximumSize(QtCore.QSize(999, 999))
        self.stackedWidget.setStyleSheet("background-color:black;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.general_page = QtWidgets.QWidget()
        self.general_page.setStyleSheet("background-color:black;")
        self.general_page.setObjectName("general_page")
        self.general_apply_button = QtWidgets.QPushButton(parent=self.general_page)
        self.general_apply_button.setGeometry(QtCore.QRect(500, 433, 141, 31))
        self.general_apply_button.setStyleSheet("QPushButton{\n"
"    background-color:#1F1F1F;\n"
"    color:white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #484848;\n"
"}")
        self.general_apply_button.setObjectName("general_apply_button")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.general_page)
        self.layoutWidget_2.setGeometry(QtCore.QRect(50, 190, 421, 121))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.vgeneral_bottom_layout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.vgeneral_bottom_layout.setContentsMargins(0, 0, 0, 0)
        self.vgeneral_bottom_layout.setObjectName("vgeneral_bottom_layout")
        self.general_mal_inf_title = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        self.general_mal_inf_title.setFont(font)
        self.general_mal_inf_title.setStyleSheet("color:white;")
        self.general_mal_inf_title.setObjectName("general_mal_inf_title")
        self.vgeneral_bottom_layout.addWidget(self.general_mal_inf_title)
        self.ggeneral_bottom_layout = QtWidgets.QGridLayout()
        self.ggeneral_bottom_layout.setHorizontalSpacing(6)
        self.ggeneral_bottom_layout.setObjectName("ggeneral_bottom_layout")
        self.general_last_upt_title = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.general_last_upt_title.setFont(font)
        self.general_last_upt_title.setStyleSheet("color:white;")
        self.general_last_upt_title.setObjectName("general_last_upt_title")
        self.ggeneral_bottom_layout.addWidget(self.general_last_upt_title, 2, 0, 1, 1)
        self.general_tot_domain_label = QtWidgets.QLabel(parent=self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.general_tot_domain_label.sizePolicy().hasHeightForWidth())
        self.general_tot_domain_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.general_tot_domain_label.setFont(font)
        self.general_tot_domain_label.setStyleSheet("color:#777777;")
        self.general_tot_domain_label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.general_tot_domain_label.setWordWrap(True)
        self.general_tot_domain_label.setObjectName("general_tot_domain_label")
        self.ggeneral_bottom_layout.addWidget(self.general_tot_domain_label, 0, 2, 1, 1)
        self.general_tot_ip_title = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.general_tot_ip_title.setFont(font)
        self.general_tot_ip_title.setStyleSheet("color:white;")
        self.general_tot_ip_title.setObjectName("general_tot_ip_title")
        self.ggeneral_bottom_layout.addWidget(self.general_tot_ip_title, 1, 0, 1, 1)
        self.general_tot_ip_label = QtWidgets.QComboBox(parent=self.layoutWidget_2)
        self.general_tot_ip_label.setObjectName("general_tot_ip_label")
        self.ggeneral_bottom_layout.addWidget(self.general_tot_ip_label, 1, 2, 1, 1)
        self.general_last_upt_label = QtWidgets.QComboBox(parent=self.layoutWidget_2)
        self.general_last_upt_label.setObjectName("general_last_upt_label")
        self.ggeneral_bottom_layout.addWidget(self.general_last_upt_label, 2, 2, 1, 1)
        self.general_colon4 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.general_colon4.setFont(font)
        self.general_colon4.setStyleSheet("color:white;")
        self.general_colon4.setObjectName("general_colon4")
        self.ggeneral_bottom_layout.addWidget(self.general_colon4, 0, 1, 1, 1)
        self.general_colon5 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.general_colon5.setFont(font)
        self.general_colon5.setStyleSheet("color:white;")
        self.general_colon5.setObjectName("general_colon5")
        self.ggeneral_bottom_layout.addWidget(self.general_colon5, 1, 1, 1, 1)
        self.general_colon6 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.general_colon6.setFont(font)
        self.general_colon6.setStyleSheet("color:white;")
        self.general_colon6.setObjectName("general_colon6")
        self.ggeneral_bottom_layout.addWidget(self.general_colon6, 2, 1, 1, 1)
        self.general_tot_domain_title = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.general_tot_domain_title.setFont(font)
        self.general_tot_domain_title.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.general_tot_domain_title.setStyleSheet("color:white;")
        self.general_tot_domain_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.general_tot_domain_title.setObjectName("general_tot_domain_title")
        self.ggeneral_bottom_layout.addWidget(self.general_tot_domain_title, 0, 0, 1, 1)
        self.vgeneral_bottom_layout.addLayout(self.ggeneral_bottom_layout)
        self.layoutWidget = QtWidgets.QWidget(parent=self.general_page)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 60, 251, 115))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vgeneral_top_layout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vgeneral_top_layout.setContentsMargins(0, 0, 0, 0)
        self.vgeneral_top_layout.setObjectName("vgeneral_top_layout")
        self.general_information_title = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        self.general_information_title.setFont(font)
        self.general_information_title.setStyleSheet("color:white;")
        self.general_information_title.setObjectName("general_information_title")
        self.vgeneral_top_layout.addWidget(self.general_information_title)
        self.ggeneral_top_layout = QtWidgets.QGridLayout()
        self.ggeneral_top_layout.setHorizontalSpacing(6)
        self.ggeneral_top_layout.setObjectName("ggeneral_top_layout")
        self.general_adapter_title = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.general_adapter_title.setFont(font)
        self.general_adapter_title.setStyleSheet("color:white;")
        self.general_adapter_title.setObjectName("general_adapter_title")
        self.ggeneral_top_layout.addWidget(self.general_adapter_title, 2, 0, 1, 1)
        self.general_ip_label = QtWidgets.QLabel(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.general_ip_label.sizePolicy().hasHeightForWidth())
        self.general_ip_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.general_ip_label.setFont(font)
        self.general_ip_label.setStyleSheet("color:#777777;")
        self.general_ip_label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.general_ip_label.setWordWrap(True)
        self.general_ip_label.setObjectName("general_ip_label")
        self.ggeneral_top_layout.addWidget(self.general_ip_label, 0, 2, 1, 1)
        self.general_status_title = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.general_status_title.setFont(font)
        self.general_status_title.setStyleSheet("color:white;")
        self.general_status_title.setObjectName("general_status_title")
        self.ggeneral_top_layout.addWidget(self.general_status_title, 1, 0, 1, 1)
        self.general_mode_cbox = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.general_mode_cbox.setObjectName("general_mode_cbox")
        self.ggeneral_top_layout.addWidget(self.general_mode_cbox, 1, 2, 1, 1)
        self.general_adapter_cbox = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.general_adapter_cbox.setObjectName("general_adapter_cbox")
        self.ggeneral_top_layout.addWidget(self.general_adapter_cbox, 2, 2, 1, 1)
        self.general_colon1 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.general_colon1.setFont(font)
        self.general_colon1.setStyleSheet("color:white;")
        self.general_colon1.setObjectName("general_colon1")
        self.ggeneral_top_layout.addWidget(self.general_colon1, 0, 1, 1, 1)
        self.general_colon2 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.general_colon2.setFont(font)
        self.general_colon2.setStyleSheet("color:white;")
        self.general_colon2.setObjectName("general_colon2")
        self.ggeneral_top_layout.addWidget(self.general_colon2, 1, 1, 1, 1)
        self.general_colon3 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.general_colon3.setFont(font)
        self.general_colon3.setStyleSheet("color:white;")
        self.general_colon3.setObjectName("general_colon3")
        self.ggeneral_top_layout.addWidget(self.general_colon3, 2, 1, 1, 1)
        self.general_ip_title = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.general_ip_title.setFont(font)
        self.general_ip_title.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.general_ip_title.setStyleSheet("color:white;")
        self.general_ip_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.general_ip_title.setObjectName("general_ip_title")
        self.ggeneral_top_layout.addWidget(self.general_ip_title, 0, 0, 1, 1)
        self.vgeneral_top_layout.addLayout(self.ggeneral_top_layout)
        self.stackedWidget.addWidget(self.general_page)
        self.about_me_page = QtWidgets.QWidget()
        self.about_me_page.setStyleSheet("background-color:grey")
        self.about_me_page.setObjectName("about_me_page")
        self.about_github_button = QtWidgets.QPushButton(parent=self.about_me_page)
        self.about_github_button.setGeometry(QtCore.QRect(440, 460, 195, 24))
        self.about_github_button.setStyleSheet("QPushButton{\n"
"    background-color:#1F1F1F;\n"
"    color:white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #484848;\n"
"}")
        self.about_github_button.setObjectName("about_github_button")
        self.stackedWidget.addWidget(self.about_me_page)
        self.mal_data_page = QtWidgets.QWidget()
        self.mal_data_page.setStyleSheet("background-color:black;")
        self.mal_data_page.setObjectName("mal_data_page")
        self.mal_detail_title2 = QtWidgets.QLabel(parent=self.mal_data_page)
        self.mal_detail_title2.setGeometry(QtCore.QRect(270, 210, 141, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        self.mal_detail_title2.setFont(font)
        self.mal_detail_title2.setStyleSheet("color:white;")
        self.mal_detail_title2.setObjectName("mal_detail_title2")
        self.mal_detail_title1 = QtWidgets.QLabel(parent=self.mal_data_page)
        self.mal_detail_title1.setGeometry(QtCore.QRect(270, 100, 192, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mal_detail_title1.sizePolicy().hasHeightForWidth())
        self.mal_detail_title1.setSizePolicy(sizePolicy)
        self.mal_detail_title1.setMinimumSize(QtCore.QSize(53, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        self.mal_detail_title1.setFont(font)
        self.mal_detail_title1.setStyleSheet("color:white;")
        self.mal_detail_title1.setObjectName("mal_detail_title1")
        self.formLayoutWidget_2 = QtWidgets.QWidget(parent=self.mal_data_page)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(280, 240, 381, 111))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.gmal_bottom_layout = QtWidgets.QGridLayout(self.formLayoutWidget_2)
        self.gmal_bottom_layout.setContentsMargins(0, 0, 0, 0)
        self.gmal_bottom_layout.setSpacing(6)
        self.gmal_bottom_layout.setObjectName("gmal_bottom_layout")
        self.mal_detail_date_title = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.mal_detail_date_title.setFont(font)
        self.mal_detail_date_title.setStyleSheet("color:white;")
        self.mal_detail_date_title.setObjectName("mal_detail_date_title")
        self.gmal_bottom_layout.addWidget(self.mal_detail_date_title, 2, 0, 1, 1)
        self.mal_detail_date_label = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mal_detail_date_label.sizePolicy().hasHeightForWidth())
        self.mal_detail_date_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.mal_detail_date_label.setFont(font)
        self.mal_detail_date_label.setStyleSheet("color:#777777;")
        self.mal_detail_date_label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.mal_detail_date_label.setText("")
        self.mal_detail_date_label.setObjectName("mal_detail_date_label")
        self.gmal_bottom_layout.addWidget(self.mal_detail_date_label, 2, 2, 1, 1)
        self.mal_detail_colon3 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.mal_detail_colon3.setFont(font)
        self.mal_detail_colon3.setStyleSheet("color:white;")
        self.mal_detail_colon3.setObjectName("mal_detail_colon3")
        self.gmal_bottom_layout.addWidget(self.mal_detail_colon3, 0, 1, 1, 1)
        self.mal_detail_type_label = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mal_detail_type_label.sizePolicy().hasHeightForWidth())
        self.mal_detail_type_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.mal_detail_type_label.setFont(font)
        self.mal_detail_type_label.setStyleSheet("color:#777777;")
        self.mal_detail_type_label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.mal_detail_type_label.setText("")
        self.mal_detail_type_label.setObjectName("mal_detail_type_label")
        self.gmal_bottom_layout.addWidget(self.mal_detail_type_label, 0, 2, 1, 1)
        self.mal_detail_desc_title = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.mal_detail_desc_title.setFont(font)
        self.mal_detail_desc_title.setStyleSheet("color:white;")
        self.mal_detail_desc_title.setObjectName("mal_detail_desc_title")
        self.gmal_bottom_layout.addWidget(self.mal_detail_desc_title, 3, 0, 1, 1)
        self.mal_detail_colon6 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.mal_detail_colon6.setFont(font)
        self.mal_detail_colon6.setStyleSheet("color:white;")
        self.mal_detail_colon6.setObjectName("mal_detail_colon6")
        self.gmal_bottom_layout.addWidget(self.mal_detail_colon6, 3, 1, 1, 1)
        self.mal_detail_source_title = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.mal_detail_source_title.setFont(font)
        self.mal_detail_source_title.setStyleSheet("color:white;")
        self.mal_detail_source_title.setObjectName("mal_detail_source_title")
        self.gmal_bottom_layout.addWidget(self.mal_detail_source_title, 0, 0, 1, 1)
        self.mal_detail_colon5 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.mal_detail_colon5.setFont(font)
        self.mal_detail_colon5.setStyleSheet("color:white;")
        self.mal_detail_colon5.setObjectName("mal_detail_colon5")
        self.gmal_bottom_layout.addWidget(self.mal_detail_colon5, 2, 1, 1, 1)
        self.mal_detail_type_title = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.mal_detail_type_title.setFont(font)
        self.mal_detail_type_title.setStyleSheet("color:white;")
        self.mal_detail_type_title.setObjectName("mal_detail_type_title")
        self.gmal_bottom_layout.addWidget(self.mal_detail_type_title, 1, 0, 1, 1)
        self.mal_detail_colon4 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.mal_detail_colon4.setFont(font)
        self.mal_detail_colon4.setStyleSheet("color:white;")
        self.mal_detail_colon4.setObjectName("mal_detail_colon4")
        self.gmal_bottom_layout.addWidget(self.mal_detail_colon4, 1, 1, 1, 1)
        self.mal_detail_source_label = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mal_detail_source_label.sizePolicy().hasHeightForWidth())
        self.mal_detail_source_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.mal_detail_source_label.setFont(font)
        self.mal_detail_source_label.setStyleSheet("color:#777777;")
        self.mal_detail_source_label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.mal_detail_source_label.setText("")
        self.mal_detail_source_label.setObjectName("mal_detail_source_label")
        self.gmal_bottom_layout.addWidget(self.mal_detail_source_label, 1, 2, 1, 1)
        self.mal_threat_level_title = QtWidgets.QLabel(parent=self.mal_data_page)
        self.mal_threat_level_title.setGeometry(QtCore.QRect(340, 60, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        self.mal_threat_level_title.setFont(font)
        self.mal_threat_level_title.setStyleSheet("background-color:#1F1F1F;\n"
"color:white;")
        self.mal_threat_level_title.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.mal_threat_level_title.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.mal_threat_level_title.setScaledContents(False)
        self.mal_threat_level_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mal_threat_level_title.setObjectName("mal_threat_level_title")
        self.mal_source_button = QtWidgets.QPushButton(parent=self.mal_data_page)
        self.mal_source_button.setEnabled(False)
        self.mal_source_button.setGeometry(QtCore.QRect(370, 450, 210, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.mal_source_button.setFont(font)
        self.mal_source_button.setStyleSheet("QPushButton{\n"
"    background-color:#1F1F1F;\n"
"    color:white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #484848;\n"
"}")
        self.mal_source_button.setObjectName("mal_source_button")
        self.mal_data_title = QtWidgets.QLabel(parent=self.mal_data_page)
        self.mal_data_title.setGeometry(QtCore.QRect(10, 20, 279, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mal_data_title.sizePolicy().hasHeightForWidth())
        self.mal_data_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        self.mal_data_title.setFont(font)
        self.mal_data_title.setStyleSheet("color:white;")
        self.mal_data_title.setObjectName("mal_data_title")
        self.mal_data_update_button = QtWidgets.QPushButton(parent=self.mal_data_page)
        self.mal_data_update_button.setGeometry(QtCore.QRect(30, 450, 210, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.mal_data_update_button.setFont(font)
        self.mal_data_update_button.setStyleSheet("QPushButton{\n"
"    background-color:#1F1F1F;\n"
"    color:white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #484848;\n"
"}")
        self.mal_data_update_button.setFlat(False)
        self.mal_data_update_button.setObjectName("mal_data_update_button")
        self.mal_first_hline = QtWidgets.QFrame(parent=self.mal_data_page)
        self.mal_first_hline.setGeometry(QtCore.QRect(270, 198, 390, 1))
        self.mal_first_hline.setStyleSheet("background-color:#1F1F1F;")
        self.mal_first_hline.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mal_first_hline.setLineWidth(0)
        self.mal_first_hline.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.mal_first_hline.setObjectName("mal_first_hline")
        self.mal_second_hline = QtWidgets.QFrame(parent=self.mal_data_page)
        self.mal_second_hline.setGeometry(QtCore.QRect(270, 438, 390, 2))
        self.mal_second_hline.setStyleSheet("background-color:#1F1F1F;")
        self.mal_second_hline.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mal_second_hline.setLineWidth(0)
        self.mal_second_hline.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.mal_second_hline.setObjectName("mal_second_hline")
        self.mal_urls_list = QtWidgets.QListWidget(parent=self.mal_data_page)
        self.mal_urls_list.setGeometry(QtCore.QRect(10, 61, 250, 379))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mal_urls_list.sizePolicy().hasHeightForWidth())
        self.mal_urls_list.setSizePolicy(sizePolicy)
        self.mal_urls_list.setStyleSheet("QListWidget {\n"
"    background-color:#1F1F1F;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    border: none;\n"
"    background-color: #1E90FF;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: #555555;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    width: 10px;\n"
"    background-color: #333333;\n"
"    border: 1px solid #555555;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #4A90E2;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background-color: #333333;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background-color: #555555;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:pressed, QScrollBar::sub-line:vertical:pressed,\n"
"QScrollBar::add-page:vertical:pressed, QScrollBar::sub-page:vertical:pressed,\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #4A90E2;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    height: 10px;\n"
"    background-color: #333333;\n"
"    border: 1px solid #555555;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #4A90E2;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    background-color: #333333;\n"
"    width: 10px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background-color: #555555;\n"
"}")
        self.mal_urls_list.setSelectionRectVisible(True)
        self.mal_urls_list.setObjectName("mal_urls_list")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.mal_data_page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(280, 130, 381, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gmal_dewtail_top_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gmal_dewtail_top_layout.setContentsMargins(0, 0, 0, 0)
        self.gmal_dewtail_top_layout.setObjectName("gmal_dewtail_top_layout")
        self.mal_detail_colon1 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.mal_detail_colon1.setFont(font)
        self.mal_detail_colon1.setStyleSheet("color:white;")
        self.mal_detail_colon1.setObjectName("mal_detail_colon1")
        self.gmal_dewtail_top_layout.addWidget(self.mal_detail_colon1, 0, 1, 1, 1)
        self.mal_detail_url_title = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.mal_detail_url_title.setFont(font)
        self.mal_detail_url_title.setStyleSheet("color:white;")
        self.mal_detail_url_title.setObjectName("mal_detail_url_title")
        self.gmal_dewtail_top_layout.addWidget(self.mal_detail_url_title, 0, 0, 1, 1)
        self.mal_detail_url_label = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.mal_detail_url_label.setFont(font)
        self.mal_detail_url_label.setStyleSheet("color:#777777;")
        self.mal_detail_url_label.setText("")
        self.mal_detail_url_label.setFrame(False)
        self.mal_detail_url_label.setObjectName("mal_detail_url_label")
        self.gmal_dewtail_top_layout.addWidget(self.mal_detail_url_label, 0, 2, 1, 1)
        self.mal_detail_resolved_ip_title = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.mal_detail_resolved_ip_title.setFont(font)
        self.mal_detail_resolved_ip_title.setStyleSheet("color:white;")
        self.mal_detail_resolved_ip_title.setObjectName("mal_detail_resolved_ip_title")
        self.gmal_dewtail_top_layout.addWidget(self.mal_detail_resolved_ip_title, 1, 0, 1, 1)
        self.mal_detail_resolved_ip_label = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.mal_detail_resolved_ip_label.setFont(font)
        self.mal_detail_resolved_ip_label.setStyleSheet("color:#777777;")
        self.mal_detail_resolved_ip_label.setFrame(False)
        self.mal_detail_resolved_ip_label.setObjectName("mal_detail_resolved_ip_label")
        self.gmal_dewtail_top_layout.addWidget(self.mal_detail_resolved_ip_label, 1, 2, 1, 1)
        self.mal_detail_colon2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.mal_detail_colon2.setFont(font)
        self.mal_detail_colon2.setStyleSheet("color:white;")
        self.mal_detail_colon2.setObjectName("mal_detail_colon2")
        self.gmal_dewtail_top_layout.addWidget(self.mal_detail_colon2, 1, 1, 1, 1)
        self.mal_detail_desc_label = QtWidgets.QLabel(parent=self.mal_data_page)
        self.mal_detail_desc_label.setGeometry(QtCore.QRect(280, 360, 381, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mal_detail_desc_label.sizePolicy().hasHeightForWidth())
        self.mal_detail_desc_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.mal_detail_desc_label.setFont(font)
        self.mal_detail_desc_label.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.mal_detail_desc_label.setStyleSheet("color:#777777;")
        self.mal_detail_desc_label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.mal_detail_desc_label.setText("")
        self.mal_detail_desc_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.mal_detail_desc_label.setWordWrap(True)
        self.mal_detail_desc_label.setObjectName("mal_detail_desc_label")
        self.stackedWidget.addWidget(self.mal_data_page)
        self.fw_rule_page = QtWidgets.QWidget()
        self.fw_rule_page.setObjectName("fw_rule_page")
        self.fw_rules_inf_title = QtWidgets.QLabel(parent=self.fw_rule_page)
        self.fw_rules_inf_title.setGeometry(QtCore.QRect(10, 20, 199, 33))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        self.fw_rules_inf_title.setFont(font)
        self.fw_rules_inf_title.setStyleSheet("color:white;")
        self.fw_rules_inf_title.setObjectName("fw_rules_inf_title")
        self.fw_rules_list = QtWidgets.QListWidget(parent=self.fw_rule_page)
        self.fw_rules_list.setGeometry(QtCore.QRect(10, 80, 250, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fw_rules_list.sizePolicy().hasHeightForWidth())
        self.fw_rules_list.setSizePolicy(sizePolicy)
        self.fw_rules_list.setStyleSheet("QListWidget {\n"
"    background-color:#1F1F1F;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    border: none;\n"
"    background-color: #1E90FF;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: #555555;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    width: 10px;\n"
"    background-color: #333333;\n"
"    border: 1px solid #555555;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #4A90E2;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background-color: #333333;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background-color: #555555;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:pressed, QScrollBar::sub-line:vertical:pressed,\n"
"QScrollBar::add-page:vertical:pressed, QScrollBar::sub-page:vertical:pressed,\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #4A90E2;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    height: 10px;\n"
"    background-color: #333333;\n"
"    border: 1px solid #555555;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #4A90E2;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    background-color: #333333;\n"
"    width: 10px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background-color: #555555;\n"
"}")
        self.fw_rules_list.setSelectionRectVisible(True)
        self.fw_rules_list.setObjectName("fw_rules_list")
        self.formLayoutWidget_3 = QtWidgets.QWidget(parent=self.fw_rule_page)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(280, 120, 381, 121))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.gfw_rules_top_layout = QtWidgets.QGridLayout(self.formLayoutWidget_3)
        self.gfw_rules_top_layout.setContentsMargins(0, 0, 0, 0)
        self.gfw_rules_top_layout.setSpacing(6)
        self.gfw_rules_top_layout.setObjectName("gfw_rules_top_layout")
        self.fw_rules_op_time_title = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.fw_rules_op_time_title.setFont(font)
        self.fw_rules_op_time_title.setStyleSheet("color:white;")
        self.fw_rules_op_time_title.setObjectName("fw_rules_op_time_title")
        self.gfw_rules_top_layout.addWidget(self.fw_rules_op_time_title, 2, 0, 1, 1)
        self.fw_rules_op_time_label = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fw_rules_op_time_label.sizePolicy().hasHeightForWidth())
        self.fw_rules_op_time_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.fw_rules_op_time_label.setFont(font)
        self.fw_rules_op_time_label.setStyleSheet("color:#777777;")
        self.fw_rules_op_time_label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.fw_rules_op_time_label.setText("")
        self.fw_rules_op_time_label.setObjectName("fw_rules_op_time_label")
        self.gfw_rules_top_layout.addWidget(self.fw_rules_op_time_label, 2, 2, 1, 1)
        self.fw_rules_colon1 = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.fw_rules_colon1.setFont(font)
        self.fw_rules_colon1.setStyleSheet("color:white;")
        self.fw_rules_colon1.setObjectName("fw_rules_colon1")
        self.gfw_rules_top_layout.addWidget(self.fw_rules_colon1, 0, 1, 1, 1)
        self.fw_rules_url_label = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fw_rules_url_label.sizePolicy().hasHeightForWidth())
        self.fw_rules_url_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.fw_rules_url_label.setFont(font)
        self.fw_rules_url_label.setStyleSheet("color:#777777;")
        self.fw_rules_url_label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.fw_rules_url_label.setText("")
        self.fw_rules_url_label.setObjectName("fw_rules_url_label")
        self.gfw_rules_top_layout.addWidget(self.fw_rules_url_label, 0, 2, 1, 1)
        self.fw_rules_current_stat_title = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.fw_rules_current_stat_title.setFont(font)
        self.fw_rules_current_stat_title.setStyleSheet("color:white;")
        self.fw_rules_current_stat_title.setObjectName("fw_rules_current_stat_title")
        self.gfw_rules_top_layout.addWidget(self.fw_rules_current_stat_title, 3, 0, 1, 1)
        self.fw_rules_colon4 = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.fw_rules_colon4.setFont(font)
        self.fw_rules_colon4.setStyleSheet("color:white;")
        self.fw_rules_colon4.setObjectName("fw_rules_colon4")
        self.gfw_rules_top_layout.addWidget(self.fw_rules_colon4, 3, 1, 1, 1)
        self.fw_rules_url_title = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.fw_rules_url_title.setFont(font)
        self.fw_rules_url_title.setStyleSheet("color:white;")
        self.fw_rules_url_title.setObjectName("fw_rules_url_title")
        self.gfw_rules_top_layout.addWidget(self.fw_rules_url_title, 0, 0, 1, 1)
        self.fw_rules_colon3 = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.fw_rules_colon3.setFont(font)
        self.fw_rules_colon3.setStyleSheet("color:white;")
        self.fw_rules_colon3.setObjectName("fw_rules_colon3")
        self.gfw_rules_top_layout.addWidget(self.fw_rules_colon3, 2, 1, 1, 1)
        self.fw_rules_ip_title = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.fw_rules_ip_title.setFont(font)
        self.fw_rules_ip_title.setStyleSheet("color:white;")
        self.fw_rules_ip_title.setObjectName("fw_rules_ip_title")
        self.gfw_rules_top_layout.addWidget(self.fw_rules_ip_title, 1, 0, 1, 1)
        self.fw_rules_colon2 = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.fw_rules_colon2.setFont(font)
        self.fw_rules_colon2.setStyleSheet("color:white;")
        self.fw_rules_colon2.setObjectName("fw_rules_colon2")
        self.gfw_rules_top_layout.addWidget(self.fw_rules_colon2, 1, 1, 1, 1)
        self.fw_rules_ip_label = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fw_rules_ip_label.sizePolicy().hasHeightForWidth())
        self.fw_rules_ip_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.fw_rules_ip_label.setFont(font)
        self.fw_rules_ip_label.setStyleSheet("color:#777777;")
        self.fw_rules_ip_label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.fw_rules_ip_label.setText("")
        self.fw_rules_ip_label.setObjectName("fw_rules_ip_label")
        self.gfw_rules_top_layout.addWidget(self.fw_rules_ip_label, 1, 2, 1, 1)
        self.fw_rules_current_stat_label = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fw_rules_current_stat_label.sizePolicy().hasHeightForWidth())
        self.fw_rules_current_stat_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.fw_rules_current_stat_label.setFont(font)
        self.fw_rules_current_stat_label.setStyleSheet("color:#777777;")
        self.fw_rules_current_stat_label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.fw_rules_current_stat_label.setText("")
        self.fw_rules_current_stat_label.setObjectName("fw_rules_current_stat_label")
        self.gfw_rules_top_layout.addWidget(self.fw_rules_current_stat_label, 3, 2, 1, 1)
        self.mal_detail_title2_2 = QtWidgets.QLabel(parent=self.fw_rule_page)
        self.mal_detail_title2_2.setGeometry(QtCore.QRect(280, 80, 141, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        self.mal_detail_title2_2.setFont(font)
        self.mal_detail_title2_2.setStyleSheet("color:white;")
        self.mal_detail_title2_2.setObjectName("mal_detail_title2_2")
        self.fw_rules_unblock_sel_data_button = QtWidgets.QPushButton(parent=self.fw_rule_page)
        self.fw_rules_unblock_sel_data_button.setEnabled(False)
        self.fw_rules_unblock_sel_data_button.setGeometry(QtCore.QRect(280, 260, 127, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.fw_rules_unblock_sel_data_button.setFont(font)
        self.fw_rules_unblock_sel_data_button.setStyleSheet("QPushButton{\n"
"    background-color:#1F1F1F;\n"
"    color:white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #484848;\n"
"}")
        self.fw_rules_unblock_sel_data_button.setFlat(False)
        self.fw_rules_unblock_sel_data_button.setObjectName("fw_rules_unblock_sel_data_button")
        self.fw_rules_unblock_all_button = QtWidgets.QPushButton(parent=self.fw_rule_page)
        self.fw_rules_unblock_all_button.setEnabled(True)
        self.fw_rules_unblock_all_button.setGeometry(QtCore.QRect(281, 291, 95, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.fw_rules_unblock_all_button.setFont(font)
        self.fw_rules_unblock_all_button.setStyleSheet("QPushButton{\n"
"    background-color:#1F1F1F;\n"
"    color:white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #484848;\n"
"}")
        self.fw_rules_unblock_all_button.setFlat(False)
        self.fw_rules_unblock_all_button.setObjectName("fw_rules_unblock_all_button")
        self.fw_rules_block_all_button = QtWidgets.QPushButton(parent=self.fw_rule_page)
        self.fw_rules_block_all_button.setEnabled(False)
        self.fw_rules_block_all_button.setGeometry(QtCore.QRect(281, 321, 81, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.fw_rules_block_all_button.setFont(font)
        self.fw_rules_block_all_button.setStyleSheet("QPushButton{\n"
"    background-color:#1F1F1F;\n"
"    color:white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #484848;\n"
"}")
        self.fw_rules_block_all_button.setFlat(False)
        self.fw_rules_block_all_button.setObjectName("fw_rules_block_all_button")
        self.fw_rules_block_new_button = QtWidgets.QPushButton(parent=self.fw_rule_page)
        self.fw_rules_block_new_button.setGeometry(QtCore.QRect(281, 351, 91, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.fw_rules_block_new_button.setFont(font)
        self.fw_rules_block_new_button.setStyleSheet("QPushButton{\n"
"    background-color:#1F1F1F;\n"
"    color:white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #484848;\n"
"}")
        self.fw_rules_block_new_button.setFlat(False)
        self.fw_rules_block_new_button.setObjectName("fw_rules_block_new_button")
        self.stackedWidget.addWidget(self.fw_rule_page)
        self.statistic_page = QtWidgets.QWidget()
        self.statistic_page.setObjectName("statistic_page")
        self.stackedWidget.addWidget(self.statistic_page)
        self.general_version_label = QtWidgets.QLabel(parent=self.menu_page)
        self.general_version_label.setGeometry(QtCore.QRect(10, 470, 95, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.general_version_label.sizePolicy().hasHeightForWidth())
        self.general_version_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.general_version_label.setFont(font)
        self.general_version_label.setStyleSheet("color:#777777;")
        self.general_version_label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.general_version_label.setObjectName("general_version_label")
        self.hmain_layout.addWidget(self.menu_page)
        self.hmain_layout.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_general_button.setText(_translate("MainWindow", "General"))
        self.menu_mal_data_button.setText(_translate("MainWindow", "Malicious Data"))
        self.menu_fw_button.setText(_translate("MainWindow", "Firewall Rules List"))
        self.menu_stat_button.setText(_translate("MainWindow", "Statistics"))
        self.general_apply_button.setText(_translate("MainWindow", "Apply Changes"))
        self.general_mal_inf_title.setText(_translate("MainWindow", "Received Malicious Data Information"))
        self.general_last_upt_title.setText(_translate("MainWindow", "Last Update Time"))
        self.general_tot_domain_label.setText(_translate("MainWindow", "255.255.255.255"))
        self.general_tot_ip_title.setText(_translate("MainWindow", "Total Number of Malicious IPS"))
        self.general_colon4.setText(_translate("MainWindow", ":"))
        self.general_colon5.setText(_translate("MainWindow", ":"))
        self.general_colon6.setText(_translate("MainWindow", ":"))
        self.general_tot_domain_title.setText(_translate("MainWindow", "Total Number of Malicious Domains"))
        self.general_information_title.setText(_translate("MainWindow", "General Information"))
        self.general_adapter_title.setText(_translate("MainWindow", "Current Adapter"))
        self.general_ip_label.setText(_translate("MainWindow", "255.255.255.255"))
        self.general_status_title.setText(_translate("MainWindow", "Protection Mode"))
        self.general_colon1.setText(_translate("MainWindow", ":"))
        self.general_colon2.setText(_translate("MainWindow", ":"))
        self.general_colon3.setText(_translate("MainWindow", ":"))
        self.general_ip_title.setText(_translate("MainWindow", "Public IP"))
        self.about_github_button.setText(_translate("MainWindow", "GitHub"))
        self.mal_detail_title2.setText(_translate("MainWindow", "Other Information"))
        self.mal_detail_title1.setText(_translate("MainWindow", "Connectivity Information"))
        self.mal_detail_date_title.setText(_translate("MainWindow", "Date"))
        self.mal_detail_colon3.setText(_translate("MainWindow", ":"))
        self.mal_detail_desc_title.setText(_translate("MainWindow", "Description"))
        self.mal_detail_colon6.setText(_translate("MainWindow", ":"))
        self.mal_detail_source_title.setText(_translate("MainWindow", "Source        "))
        self.mal_detail_colon5.setText(_translate("MainWindow", ":"))
        self.mal_detail_type_title.setText(_translate("MainWindow", "Type"))
        self.mal_detail_colon4.setText(_translate("MainWindow", ":"))
        self.mal_threat_level_title.setText(_translate("MainWindow", "THREAT LEVEL"))
        self.mal_source_button.setText(_translate("MainWindow", "USOM Source"))
        self.mal_data_title.setText(_translate("MainWindow", "Received Malicious Data"))
        self.mal_data_update_button.setText(_translate("MainWindow", "Update Data"))
        self.mal_detail_colon1.setText(_translate("MainWindow", ":"))
        self.mal_detail_url_title.setText(_translate("MainWindow", "URL             "))
        self.mal_detail_resolved_ip_title.setText(_translate("MainWindow", "IP Address"))
        self.mal_detail_colon2.setText(_translate("MainWindow", ":"))
        self.fw_rules_inf_title.setText(_translate("MainWindow", "Firewall Rules List"))
        self.fw_rules_op_time_title.setText(_translate("MainWindow", "Operation Time"))
        self.fw_rules_colon1.setText(_translate("MainWindow", ":"))
        self.fw_rules_current_stat_title.setText(_translate("MainWindow", "Current Status"))
        self.fw_rules_colon4.setText(_translate("MainWindow", ":"))
        self.fw_rules_url_title.setText(_translate("MainWindow", "URL"))
        self.fw_rules_colon3.setText(_translate("MainWindow", ":"))
        self.fw_rules_ip_title.setText(_translate("MainWindow", "IP Address"))
        self.fw_rules_colon2.setText(_translate("MainWindow", ":"))
        self.mal_detail_title2_2.setText(_translate("MainWindow", "Other Information"))
        self.fw_rules_unblock_sel_data_button.setText(_translate("MainWindow", "Unblock Selected Data"))
        self.fw_rules_unblock_all_button.setText(_translate("MainWindow", "Unblock All Data"))
        self.fw_rules_block_all_button.setText(_translate("MainWindow", "Block All Data"))
        self.fw_rules_block_new_button.setText(_translate("MainWindow", "Block New Data"))
        self.general_version_label.setText(_translate("MainWindow", "Version 2023.10.1"))
